project:
  type: website

website:
  title: "AIR QUALITY ANALYSIS"
  navbar:
    left:
      - href: home.qmd
        text: HOME
      - href: index.qmd
        text: POLLUTANTS
      - href: dist.qmd
        text: DISTRIBUTION
      - href: aboutwf.qmd
        text: ABOUT

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



